# Generated by Django 4.0.4 on 2022-05-18 13:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone as timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, unique=True, verbose_name='城市名称')),
                ('add_time', models.DateTimeField(default=timezone.now, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '城市录入',
                'verbose_name_plural': '城市录入',
            },
        ),
        migrations.CreateModel(
            name='PlanyTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=30, unique=True, verbose_name='模板名称')),
                ('ersion_num', models.CharField(max_length=30, verbose_name='版本号')),
                ('company_name', models.CharField(max_length=30, verbose_name='编制单位')),
                ('create_user', models.CharField(max_length=30, verbose_name='编制人')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='编制时间')),
                ('use_info', models.TextField(blank=True, null=True, verbose_name='使用说明')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('add_time', models.DateTimeField(default=timezone.now, verbose_name='描述信息')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '预案模板',
                'verbose_name_plural': '预案模板',
            },
        ),
        migrations.CreateModel(
            name='PlanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30, unique=True, verbose_name='类型名称')),
                ('type_desc', models.TextField(verbose_name='类型描述')),
                ('type_status', models.BooleanField(default=1, verbose_name='类型状态')),
                ('add_time', models.DateTimeField(default=timezone.now, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '预案编制',
                'verbose_name_plural': '预案编制',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, verbose_name='预案名称')),
                ('plan_des', models.TextField(null=True, verbose_name='方案描述')),
                ('dangerous_goods_name', models.TextField(null=True, verbose_name='危险品名称')),
                ('dangerous_goods_en_name', models.TextField(null=True, verbose_name='危险品英文名称')),
                ('implementation_objectives', models.TextField(null=True, verbose_name='实施目标')),
                ('plan_implementer', models.TextField(null=True, verbose_name='预案实施人')),
                ('add_time', models.DateTimeField(default=timezone.now, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('plantype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.plans', verbose_name='预案编制')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.planytemplate', verbose_name='处理模板')),
            ],
            options={
                'verbose_name': '预案管理',
                'verbose_name_plural': '预案管理',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_name', models.CharField(max_length=30, unique=True, verbose_name='评估名称')),
                ('assessment_description', models.TextField(verbose_name='评估描述')),
                ('assessment_user', models.TextField(verbose_name='评估人')),
                ('add_time', models.DateTimeField(default=timezone.now, verbose_name='评估时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.city', verbose_name='城市名称')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.plans', verbose_name='方案名称')),
            ],
            options={
                'verbose_name': '方案评估',
                'verbose_name_plural': '方案评估',
            },
        ),
    ]
