# Generated by Django 4.0.4 on 2022-05-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name': '预案生成', 'verbose_name_plural': '预案生成'},
        ),
        migrations.AlterField(
            model_name='plans',
            name='dangerous_goods_en_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='危险品英文名称'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='dangerous_goods_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='危险品名称'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_implementer',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='预案实施人'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plantype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.planytype', verbose_name='预案编制'),
        ),
        migrations.AlterField(
            model_name='planytype',
            name='type_desc',
            field=models.TextField(verbose_name='编制描述'),
        ),
        migrations.AlterField(
            model_name='planytype',
            name='type_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='编制名称'),
        ),
        migrations.AlterField(
            model_name='planytype',
            name='type_status',
            field=models.BooleanField(default=1, verbose_name='编制状态'),
        ),
    ]
