# Generated by Django 4.0.4 on 2022-05-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_plans_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_detail',
            field=models.TextField(null=True, verbose_name='方案细节'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='implementation_objectives',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='实施目标'),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_implementer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='预案实施人'),
        ),
    ]
