# Generated by Django 4.0.4 on 2022-05-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_assessment_assessment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='file',
            field=models.FileField(default='', upload_to='upload/user', verbose_name='评估附件'),
            preserve_default=False,
        ),
    ]
