# Generated by Django 4.0.4 on 2022-05-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_assessment_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='dangerous_goods_en_name',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='dangerous_goods_name',
        ),
    ]
