# Generated by Django 4.0.4 on 2022-05-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_plans_dangerous_goods_en_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planytemplate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/user', verbose_name='详细文件'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='file',
            field=models.FileField(upload_to='upload/user', verbose_name='评估文件'),
        ),
    ]
