# Generated by Django 4.0.4 on 2022-05-20 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_planytemplate_file_alter_assessment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planytemplate',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
