# Generated by Django 4.0.4 on 2022-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_algorithm_datahouse_dataset_remove_plans_plantype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='algorithm',
            options={'verbose_name': '算法', 'verbose_name_plural': '算法'},
        ),
        migrations.AddField(
            model_name='algorithm',
            name='algorithm_num',
            field=models.CharField(default=0, max_length=30, verbose_name='算法编号'),
            preserve_default=False,
        ),
    ]
