# Generated by Django 4.0.4 on 2022-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_algorithm_options_algorithm_algorithm_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='path',
            field=models.FileField(max_length=30, upload_to='upload/algorithm_set/', verbose_name='算法文件路径'),
        ),
    ]
