# Generated by Django 4.0.4 on 2022-05-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_algorithm_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='path',
            field=models.FileField(upload_to='upload/algorithm_set/', verbose_name='算法文件路径'),
        ),
    ]
