# Generated by Django 4.0.4 on 2022-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_datahouse_algorithm_alter_datahouse_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datahouse',
            name='results1',
            field=models.FloatField(default=0, verbose_name='运行结果2'),
        ),
        migrations.AddField(
            model_name='datahouse',
            name='results2',
            field=models.FloatField(default=0, verbose_name='运行结果3'),
        ),
        migrations.AddField(
            model_name='datahouse',
            name='results3',
            field=models.FloatField(default=0, verbose_name='运行结果4'),
        ),
        migrations.AddField(
            model_name='datahouse',
            name='results4',
            field=models.FloatField(default=0, verbose_name='运行结果5'),
        ),
        migrations.AlterField(
            model_name='datahouse',
            name='results',
            field=models.FloatField(default=0, verbose_name='运行结果1'),
        ),
    ]
